### PR TITLE
Replace AndroidHttpClient with OkHttpClient

### PR DESCRIPTION
**Pull request by cketti**
OkHttp has many nice features built-in and a nicer API. Check the [OkHttp website](http://square.github.io/okhttp/) for more details.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@cketti I reviewed your changes and they look good to me. I am happy to merge them for a redeployment of this app which I will release in a few days. Can you please address the following issues to enable a clean merge:

* Rebase onto current master of `tuxmobil/CampFahrplan`.
* Update [*OkHttp*](http://square.github.io/okhttp/) to the latest version in commit b3f2c29595f8b93deaafe006faf851f03dd26c0a.
* Apply your build script changes of commit 8f546f1768689587f586bef5b187f71219c20963 to the `camp2015` flavor as well.

Feel free to rewrite the history of your branch to produce clean commits!

**Comment by cketti** [comment]
Will do.

**Comment by johnjohndoe** [comment]
@cketti I would need it within the next 24 hours to include it. Just let me know if you have time.

**Comment by cketti** [comment]
Sorry, it's unlikely I'll find the time to do it before the weekend.

**Comment by johnjohndoe** [comment]
@cketti Would be great if you can rebase this onto master before 11/16/15.

**Comment by johnjohndoe** [comment]
@tuxmobil I updated (latest version of [*OkHttp*](http://square.github.io/okhttp/), updated configuration for `camp2015` flavor) and rebased this branch onto current master: https://github.com/johnjohndoe/CampFahrplan/tree/okhttp

**Comment by tuxmobil** [comment]
Thanks. Github shows merge conflicts, though.

**Comment by tuxmobil** [comment]
done

**Comment by johnjohndoe** [comment]
Merged [here](https://github.com/tuxmobil/CampFahrplan/commit/ef5677609435f4a036dcfa578004af25f8c8abbb).

**Pull request closed without merging**
