### PR TITLE
Sharedpreferences

### PR DESCRIPTION
**Pull request by johnjohndoe**
In this branch I aimed to unify and encapsulated the access to shared preferences using the [TypedPreferences library](https://github.com/johnjohndoe/TypedPreferences).

### CODE REVIEW

**Comment by tuxmobil** [comment]
I still have to make up my mind whether I like to have an additional external library.

**Comment by johnjohndoe** [comment]
You don't like external libraries? There are tons of them out there. Some are really useful. I wrote this one.

**Comment by johnjohndoe** [comment]
I further worked on this branch. I refactored the preferences so that **default values** are no longer defined in multiple locations.

Two things that still puzzle me:
1. Preference **keys** are defined in **multiple places**: _PreferencesHelper.java_, _SettingsActivity.java_ _prefs.xml_.
2. Preference **keys** in these locations **differ** from each other.
   
   | prefs.xml | SettingsActivity | PreferencesHelper | introduced |
   | :-- | :-- | :-- | :-- |
   | `alternative_highlight` | `alternative_highlight` | `nerd.tuxmobil.fahrplan.congress.Prefs.ALTERNATIVE_HIGHLIGHT` | bcd4d3b484a02d81fd9e4baaaf5e2390ee140f2b |
   | `default_alarm_time` | `default_alarm_time` | `nerd.tuxmobil.fahrplan.congress.Prefs.ALARM_TIME_INDEX` | 01ab865496356e78339e1751b99de73092b532e5 |
   | `schedule_url` | `schedule_url` | `nerd.tuxmobil.fahrplan.congress.Prefs.SCHEDULE_URL` | d387a4f8f4e9ea17328416cbc72d9c2202494a |

**Comment by johnjohndoe** [comment]
:x: Not ready to merge. Might be reimplemented in the future.

**Pull request closed without merging**
