### PR TITLE
Add Navigation via C3Nav as Action in EventDetail

### PR DESCRIPTION
**Pull request by ligi**

### CODE REVIEW

**Comment by ligi** [comment]
should be merged after #117

**Comment by tuxmobil** [comment]
just from looking at the changed files: no german strings?

**Comment by ligi** [comment]
Yes - no german strings - could not think of a good translations and
everyone at the congress should understand english

**Comment by johnjohndoe** [comment]
How about: "Navigiere", "Route"?

**Comment by ligi** [comment]
OK - I trust you with this one and added "Navigiere" as translation

**Comment by johnjohndoe** [comment]
Here is a list of all rooms which (to my knowledge) can appear in this app - please make sure they are supported:

* Anarchist Village
* Bühne
* Free Software Foundation Europe
* Hall 13
* Hall 14
* Hall 1
* Hall 2
* Hall 6
* Hall A.1
* Hall A.2
* Hall B
* Hall C.1
* Hall C.2
* Hall C.3
* Hall C.4
* Hall F
* Hall G
* HardwareHackingArea
* Podcaster-Tisch

**Comment by ligi** [comment]
How do you get to the other locations? I only see Hall1,Hall2,HallG,Hall 6

On 25.12.2015 11:45, Tobias Preuss wrote:
> Here is a list of all rooms which (to my knowledge) can appear in this
> app - please make sure they are supported:
> 
>   * Anarchist Village
>   * Bühne
>   * Free Software Foundation Europe
>   * Hall 13
>   * Hall 14
>   * Hall 1
>   * Hall 2
>   * Hall 6
>   * Hall A.1
>   * Hall A.2
>   * Hall B
>   * Hall C.1
>   * Hall C.2
>   * Hall C.3
>   * Hall C.4
>   * Hall F
>   * Hall G
>   * HardwareHackingArea
>   * Podcaster-Tisch
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tuxmobil/CampFahrplan/pull/118#issuecomment-167221635>.
> 


-- 
best regards,
ligi
http://ligi.de

**Comment by johnjohndoe** [comment]
There exists an extended version of the schedule generated by the [re-data](https://github.com/opendatacity/re-data) project. They parse the *self organized sessions* from the wiki and include them in a larger "everything" schedule file. You can manually switch to this schedule file by entering the URL manually in the settings / *Alternative schedule URL*. However, currently the extended schedule is not available since people are still working on it. I have a older copy of the file and can send it to you.

**Comment by ligi** [comment]
No wonder I could not find it .. - OK please send it to me

**Comment by johnjohndoe** [comment]
Sent. For completeness I link the [session locations in the 32c3 wiki](https://events.ccc.de/congress/2015/wiki/Category:Session_location).

**Comment by ligi** [comment]
Hm I think I will have to make a white-list - maybe I am not able to resolve everything - like Podcaster-Tisch - is it in the Sendezentrum?
Will then just show the navigation-item if I can resolve the room

**Comment by NoMoKeTo** [comment]
@ligi I can add any missing locations to c3nav. (Apart from that, you can even link to exact coordinates: https://c3nav.de/?d=0:600:500)

**Comment by ligi** [comment]
Great! I would still need to know where this  Podcaster-Tisch is - will dig into this tonight

**Comment by johnjohndoe** [comment]
> ... where this Podcaster-Tisch is ...

I could not find it in the wiki - even not if I am signed in. Maybe the easiest would be to contact someone in person per mail. @ligi You will find a few user names in the XML file I sent you.

**Comment by ligi** [comment]
Just resolved some more rooms and gave respect to the venue - should cover most cases and other rooms can be added easily later

**Comment by tuxmobil** [comment]
merged in 2bdc42af0d060cea935a19409a128983a1f28f63

**Pull request closed without merging**
