### PR TITLE
Simplify gradle file and use SDK 23/Appcompat 23.1.1

### PR DESCRIPTION
**Pull request by ligi**
This iterating over the variants/outputs is not needed anymore - there is now a way more elegant way to do the same

### CODE REVIEW

**Comment by johnjohndoe** [comment]
If the simplification does not depend on SDK 23 I would prefer to split the changes into two separate commits.

**Comment by ligi** [comment]
Why?

**Comment by johnjohndoe** [comment]
Separation of concerns. The SDK 23 update might introduce changes that cannot be forseen. This has nothing to do with the simplification as I understood.

**Comment by ligi** [comment]
I do not see the advantage in splitting this

**Comment by johnjohndoe** [comment]
Separate concerns allows for cherry-picking to other branches, easier debugging to find the exact commit which causes the error (divide and conquer as in Git bisect).

**Comment by ligi** [comment]
I understand this - still do not see the advantage for this particular
commit - added you as collaborator - you can change the branch if you
want  - I will not waste time with this

**Comment by johnjohndoe** [comment]
I split the commit and opened two separate pull requests here: #119 and #120.

**Comment by ligi** [comment]
closing this one then

**Pull request closed without merging**
