### PR TITLE
Simplify gradle file.

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by tuxmobil** [comment]
This fails on my machine with

**Comment by johnjohndoe** [comment]
@ligi I cannot reproduce this - can you?

**Comment by ligi** [comment]
you get this when your signing config is invalid - Not a fan of this
being mandatory anyway - it increases the friction for new coders when
they just want to adjust a simple thing they have to edit property-files
and create signing-keys to just compile the project - but this is also
the case without this PR

**Comment by tuxmobil** [comment]
thanks, just found out for myself that I accidentially broke it

**Pull request merged**
