### PR TITLE
amend the app for the Camp2015

### PR DESCRIPTION
**Pull request by SubOptimal**
- links and text amended for the Camp2015
- as the current version of dependency "com.afollestad:material-dialogs" isn't backward compatible to the used version 0.4.6 a link to a maven repository which holds version 0.4.6 has been added

If you publish an updated version of the app to Google Play, would you please also update the Wiki page https://events.ccc.de/camp/2015/wiki/Apps .

### CODE REVIEW

**Comment by benerudolph** [comment]
I was able to build the app successfully, however for current android SDK I had to increase ```buildToolsVersion "21.1.2"``` in /app/build.gradle. Could you make this like 21.1.+?

**Comment by SubOptimal** [comment]
@benerudolph see the commit 9d6fa3c. It will choose the most recent installed build tools >= 21.1.1 for the build.

**Comment by johnjohndoe** [comment]
@SubOptimal In my case the app crashes immediately after fetching the schedule. This happens because the ```<track/>``` element has not been filled out in the XML file.

**Comment by SubOptimal** [comment]
@johnjohndoe Please try again with the lastest source version. It should be fixed now.

**Pull request closed without merging**
