### PR TITLE
Fix setting non-default alarm time.

### PR DESCRIPTION
**Pull request by johnjohndoe**
- Resolves issue #135.
- Bug introduced in 98a34ca4305ca138fefb079d8d21ce0cc6ad7b79.

### CODE REVIEW

**Comment by tuxmobil** [comment]
Wouldn't it be more straight forward to use an integer-array then?

**Comment by johnjohndoe** [comment]
That is not possible to what I researched. I was also surprised. This is actually the reason for the bug. I was using an int array in XML before.

**Comment by tuxmobil** [comment]
http://developer.android.com/guide/topics/resources/more-resources.html#IntegerArray
does not work?

**Comment by johnjohndoe** [comment]
Yes, I am aware of this. I could not use it with the widget though.

**Comment by tuxmobil** [comment]
Do you mean in SettingsActivity.java? If I'm right, you're comparing with an integer there too, so this would become simpler also.

**Comment by johnjohndoe** [comment]
The attribute `android:entryValues` in `ListPreference` in _prefs.xml_ expects a string array. I could not find this fact in the [documentation](http://developer.android.com/reference/android/preference/ListPreference.html) but on several other websites.

**Comment by johnjohndoe** [comment]
@tuxmobil From what I researched it is common practice to use a `string-array`:
- [Issue #2096 - Expand ListPreference to support alternate array types](https://code.google.com/p/android/issues/detail?id=2096)
- [Google search for "android ListPreference int-array"](http://bfy.tw/3bZO)

**Comment by johnjohndoe** [comment]
:white_check_mark: Merged here: https://github.com/EventFahrplan/EventFahrplan/commit/113f42ff7789746a80d471026220aacb8edf1d58

**Pull request closed without merging**
