### PR TITLE
Event drawable

### PR DESCRIPTION
**Pull request by johnjohndoe**
This branch refactors the way event items in the schedule view are created. It is no longer necessary to **manually create XML files** for each individual track to have custom colors defined. Please note the number of **XML files being deleted** by this pull request. The new _EventDrawable_ class **programmatically** creates drawables for the respective event.

Previous work has been done in the former "feature/simplify-handling-track-background-colors" branch aka https://github.com/johnjohndoe/CampFahrplan/commit/ba8680fef6d14497499d5220f389f0fdcb7764d2. I extracted the **creation of drawables** from that branch and rewrote the implementation.

I am happy to read your thoughts on this. As always I am happy to rebase the branch if new commits are being introduced onto master in the meantime.

### CODE REVIEW

**Comment by tuxmobil** [comment]
Hmm. I actually like to be able to create/edit/preview layouts based on XML files.

**Comment by johnjohndoe** [comment]
I agree: previewing XML layouts is useful in most cases. But in this case their is no real benefit as you can see from the screenshot.

### Preview of app/src/ccc32c3/res/drawable/event_item_default_science.xml

XML layout preview

**Comment by tuxmobil** [comment]
Ok. I misunderstood that you wanted to also create the event layout programmatically, not just the background.

**Comment by johnjohndoe** [comment]
:white_check_mark: Merged here: https://github.com/EventFahrplan/EventFahrplan/commit/eade89c44ccc75570bb6fa0a030c140646da61ea

**Pull request closed without merging**
